In [31]:
# Do not change the path of this notebook (do not use %cd)
from PIL import Image

print("GTA5 dataset")
img = Image.open('/home/mateusw/repos/domain_adaptation_semantic_segmentation/data/GTA5/labels/00001.png')
print(img.mode)

print("Cityscapes dataset")
img = Image.open('data/Cityscapes/Cityspaces/gtFine/train/hanover/hanover_000000_000164_gtFine_labelTrainIds.png')
print(img.mode)

GTA5 dataset
P
Cityscapes dataset
L


# Prepare Enviroment

In [32]:

#!git clone https://github.com/MateusWiteck/domain_adaptation_semantic_segmentation.git


In [33]:
%run train.py

In [34]:
# Download Citiescapes Dataset:
#!pip install -q gdown
#!gdown --id 1Qb4UrNsjvlU-wEsR9d7rckB0YS_LXgb2 --output Cityscapes.zip
#!unzip Cityscapes.zip -d domain_adaptation_semantic_segmentation/data/


In [35]:
# Download GTA Dataset:
#!pip install -q gdown
#!gdown --id 1xYxlcMR2WFCpayNrW2-Rb7N-950vvl23 --output GTA5.zip
#!unzip GTA5.zip -d domain_adaptation_semantic_segmentation/data/


# Dataset and Dataloader

Here we should:
- Convert the GTA5 labels to the same format of the Cityscapes dataset (https://github.com/sarrrrry/PyTorchDL_GTA5/blob/master/pytorchdl_gta5/labels.py)
- Create the Datasets class for each one
- Create the DataLoader
- Define the train test val ? division

## Cityscapes

In [2]:
%run datasets/cityscapes.py


Output in numpy array format:
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
Output in tensor format:
tensor([[255, 255, 255,  ..., 255, 255, 255],
        [255, 255, 255,  ..., 255, 255, 255],
        [255, 255, 255,  ..., 255, 255, 255],
        ...,
        [255, 255, 255,  ..., 255, 255, 255],
        [255, 255, 255,  ..., 255, 255, 255],
        [255, 255, 255,  ..., 255, 255, 255]], dtype=torch.int32)
Shape of label tensor:
torch.Size([1024, 2048])


bsdafkjsdkañjflkdajsñodjñfoiajsdi


## GTA5


In [37]:
%cd /content/

[Errno 2] No such file or directory: '/content/'
/home/mateusw/repos/domain_adaptation_semantic_segmentation


In [38]:
%run datasets/gta5.py

Output in numpy array format:
[[ 10  10  10 ...  10  10  10]
 [ 10  10  10 ...  10  10  10]
 [ 10  10  10 ...  10  10  10]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
Output in tensor format:
tensor([[ 10,  10,  10,  ...,  10,  10,  10],
        [ 10,  10,  10,  ...,  10,  10,  10],
        [ 10,  10,  10,  ...,  10,  10,  10],
        ...,
        [  0,   0,   0,  ..., 255, 255, 255],
        [  0,   0,   0,  ..., 255, 255, 255],
        [  0,   0,   0,  ..., 255, 255, 255]])
Shape of label tensor:
torch.Size([1052, 1914])


In [39]:
gta5_dataset = GTA5("data/GTA5/",
                    transform=None,
                    label_transform= None)


In [ ]:
#%cd domain_adaptation_semantic_segmentation/
#!git pull
#!git fetch --all
#%cd ..

[Errno 2] No such file or directory: 'domain_adaptation_semantic_segmentation/'
/home/mateusw/repos/domain_adaptation_semantic_segmentation
Enter passphrase for key '/home/mateusw/.ssh/id_ed25519': 
^C
/home/mateusw/repos
